festi = {
    "01.01" : "Happy New Year!",
    "01.26" : "Happy Republic day!",
    "03.11" : "Happy Maha Shivarathri!",
    "04.01" : "This is the day for all you fools.",
    "04.02" : "Happy Easter!",
    "04.14" : "Happy Vishu!",
    "05.01" : "Greetings on May Day!",
    "05.12" : "Eid-ul Fitr Mubarak!",
    "06.20" : "Eid al Adha Mubarak!",
    "07.15" : "Happy Indipendance Day!",
    "07.20" : "എല്ലാവർക്കും എന്റെ ഹൃദയം നിറഞ്ഞ തിരുവോണാശംസകൾ !",
    "07.23" : "Greetings on Sree Narayana Guru Jayanti!",
    "09.21" : "Greetings on Sree Narayana Guru Samadhi",
    "10.02" : "Greetings on Gandhi Jayanti!",
    "10.14" : "Happy Maha Navami!",
    "10.15" : "Happy Vijaya Dashami!",
    "10.19" : "Greetings on Eid e Milad!",
    "11.04" : "May this Diwali light up your life! Happy Diwali to all of you!",
    "12.25" : "Merry Christmas to all of you!"
}